### ISSUE TITLE
重力変数の、位置更新の計算がgt^2でなくgt

### ISSUE THREAD

**Issue by monguri** [pafuhana1213/KawaiiPhysics#10]
AnimNode_KawaiiPhysics.cppの重力処理が以下のようになっていました。
		// Gravity
		// TODO:Migrate if there are more good method (Currently copying AnimDynamics implementation)
		Bone.Location += Gravity * DeltaTime;

AnimDynamicsの処理を見たとことろAnimPhysSolver.cppで以下のようになっていました。
	FVector Force = InBody->bUseGravityOverride ? (InBody->GravityOverride * InBody->Mass) : (GravityDirection * FMath::Abs(UPhysicsSettings::Get()->DefaultGravityZ) * InBody->Mass * InBody->GravityScale);
	InBody->LinearMomentum += Force * DeltaTime;
	InBody->NextPosition = InBody->Pose.Position + InBody->LinearMomentum * InBody->InverseMass * DeltaTime;
Gravityに対してはDeltaTimeの2乗を乗算した上で位置の次元の変数に代入するような次元の扱いとなっていました。

どちらであっても、アーティストのGravityの設定次第で同じような動きが達成されると思うので、あくまで私の意見になりますが、タイムステップの2乗になっていた方が自由落下に近い動きをするときによりリアルな動きになるかもしれません。

**Comment by pafuhana1213** [comment]
ご報告ありがとうございます！

gt^2 の方が物理的に正しいので、v1.4.0で修正しました。
1.3.1以前の重力計算を使用したい場合は　p.KawaiiPhysics.EnableOldPhysicsMethodGravity を 1 に設定してください
https://github.com/pafuhana1213/KawaiiPhysics/commit/2e9b5773075968230b3c2c2d960e1669038971ca

**Comment by monguri** [comment]
ありがとうございます！
