### ISSUE TITLE
pelvisからspine3まで子boneをつけるとPhysicsがおかしくなる

### ISSUE THREAD

**Issue by cogaram** [pafuhana1213/KawaiiPhysics#100]
Blenderでauto rig proを使ってます。

pelvisからspine3までどのボーンに子ボーンを入れた状態
editorでは問題が見当たりませんがPackageすると何故かおかしくなります

physicsが作動しなかったり当たり判定が妙なとこで作動したりとかの状態になります。

pelvisからspine3以外のボーンでは今のところ問題が見当たりませんでした。

**Comment by pafuhana1213** [comment]
頂いた情報だけですと、問題を再現・特定できないため、どのように修正・対応すべきかが分からないというのが正直な所です。

問題を再現するための詳細な手順やプロジェクトなど問題解決に向けて、可能な範囲で情報・データをいただけますと助かります。
よろしくお願いいたします。
