### ISSUE TITLE
expose as a pin for limits data asset

### ISSUE THREAD

**Issue by wdw89** [pafuhana1213/KawaiiPhysics#110]
Is it possible to expose as a pin for limits data asset? it is helpful for setting different size character sharing same skeleton. So I can use variable to set different value in Linked Anim Graph node.

**Comment by pafuhana1213** [comment]
I've adopted your great request now!
https://github.com/pafuhana1213/KawaiiPhysics/discussions/112

Thanks @wdw89 !
