### ISSUE TITLE
Crash in Editmode of Data Asset Limits

### ISSUE THREAD

**Issue by rudtjq640** [pafuhana1213/KawaiiPhysics#119]
While setting up Limits Collider through Data Asset, I founded a bug.
In the same way, I could see that Crash occurred.

First. Create new Limits in Data Asset, allocate Bone, and do not press Save.

Second. In the View of the Animation blueprint, Limits Collider is visible without saving the Data Asset.

Third, click on the visible Limits Collider, hold the XYZ axis directly within the View, and raise the Position, Rotate, and Scale values, and a crash occurs.

The content of Crash seems to be a crash because the newly generated array and index do not match
Fortunately, if you press Save and hold the XYZ axis and move it, there will be no crash.

I was trying to fix it myself, but strangely, the DoScale function still causes problems...!

--- Crash Message
Assertion failed: (Index >= 0) & (Index < ArrayNum)
Engine\Engine\Source\Runtime\Core\Public\Containers\Array.h] [Line: 752] Array index out of bounds: 1 from an array of size 1

![Screenshot_57](https://github.com/pafuhana1213/KawaiiPhysics/assets/96940180/b9ea7f65-0788-4d9d-a85f-79cebe60a6c2)
![Screenshot_58](https://github.com/pafuhana1213/KawaiiPhysics/assets/96940180/00f24599-7343-4120-8bc9-ac62fba7f174)

--- I tried fixing code (but is failed. i'm still crash in DoScale Function)
![Screenshot_60](https://github.com/pafuhana1213/KawaiiPhysics/assets/96940180/d52c798a-e694-4242-ae69-84165ccc3567)
![Screenshot_61](https://github.com/pafuhana1213/KawaiiPhysics/assets/96940180/ba88e649-363c-44fa-87c0-56638919ed9c)

![Screenshot_59](https://github.com/pafuhana1213/KawaiiPhysics/assets/96940180/bf4e3195-4e3c-40d2-901e-afa0157a4edb)

**Comment by rudtjq640** [comment]
I was fixing it in KawaiiPhysicsEditMode.cpp file

**Comment by pafuhana1213** [comment]
Hi @rudtjq640,
Thanks for your report and codes!

I have fixed this issue with the following code now. Would you please check out this?
https://github.com/pafuhana1213/KawaiiPhysics/commit/0ce49d9acb04d82c9a2881040db59065c813ad30

thanks
