### ISSUE TITLE
Spherical/Capsule/Planar shapes are not showing up 

### ISSUE THREAD

**Issue by LimiHJ** [pafuhana1213/KawaiiPhysics#127]
I was adding Date asset somehow when I add Capsule root bone nothing appear.  The Debug visualization is not working neither, not sure if I need to update anything or I haven't turned on some settings.

**Comment by pafuhana1213** [comment]
Hi @LimiHJ ,
Would you please tell me which version you are using ? Also, could you please provide more detailed steps to reproduce the issue?

thanks!

**Comment by pafuhana1213** [comment]
I'm closing this thread because it doesn't happen in my environment. 
If you want to resume it, would you please reopen it?

Thank you!
