### ISSUE TITLE
Can't compile against engine source

### ISSUE THREAD

**Issue by shimizu-izumi** [pafuhana1213/KawaiiPhysics#129]
I'm currently working on a custom engine build for the team I'm working with and wanted to include KawaiiPhysics by default, the problem is I can't compile an installed build with the newest KawaiiPhysics version. The engine source I used is the latest release version.

<details>
<summary>Errors</summary>
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(196): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(198): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(200): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(203): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(206): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(208): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(210): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(212): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(214): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(216): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(218): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(220): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(222): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\AnimNode_KawaiiPhysics.h(682): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsCustomExternalForce.h(13): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsCustomExternalForce.h(16): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsCustomExternalForce.h(37): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(37): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(40): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(47): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(54): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(57): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(60): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(170): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(179): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(182): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(219): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(226): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(233): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(236): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(240): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(265): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(276): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(283): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(287): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsExternalForce.h(296): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
D:\Development\UnrealEngine\Engine\Plugins\Animation\KawaiiPhysics\Source\KawaiiPhysics\Public\KawaiiPhysicsLimitsDataAsset.h(21): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
</details

**Comment by pafuhana1213** [comment]
Hi @shimizu-izumi 
Would you please try to place the KawaiiPhysics folder in your **project's** Plugins folder?

thanks!

**Comment by shimizu-izumi** [comment]
Sure, I can do that.
I was just a bit confused because compiling against the engine source worked in the past.

**Comment by pafuhana1213** [comment]
Hi @shimizu-izumi 

I've comitted https://github.com/pafuhana1213/KawaiiPhysics/commit/32b5f02fc82ef31e41e42e146acef617ed759abc to fix this issue. 
Would you please try it? Thanks!

**Comment by shimizu-izumi** [comment]
I got two new errors that way, I hope I fixed them to your liking and can confirm that I was able to create an installed build of 5.4.3 with it.

**Comment by pafuhana1213** [comment]
Thanks for your great help!
I've accepted your pull request now!
