### ISSUE TITLE
[BUG]特定のプラットフォームでコンパイルを行う際にAnimNode_KawaiiPhysics.cppでコンパイルエラーが発生する

### ISSUE THREAD

**Issue by TojiroIwamoto** [pafuhana1213/KawaiiPhysics#139]
表題の通り、PCではない特定のプラットフォーム向けにコンパイルする際にビルドエラーが発生します
あまり詳しくご説明できず恐縮ですが、コードの修正例も一緒に張り付けます

** 再現環境 -  Environment
Engine version :UE5.4.3 
Plugin version : 1.17.1
Microsoft Visual Studio Professional 2022 17.9.5 C++

**スクリーンショット または動画 - Screenshots or Movies**
![image](https://github.com/user-attachments/assets/b422aaa0-6e87-498b-9b5a-42a36e14fe02)

**その他 - Additional context**
AnimNode_KawaiiPhysics.cppの497行目辺りにある以下のコードを
`for (const auto BodySetup : PhysicsAssetForLimits->SkeletalBodySetups)`

`for (const auto& BodySetup : PhysicsAssetForLimits->SkeletalBodySetups)`
にする事でエラーを除去できます

![image](https://github.com/user-attachments/assets/74014eea-a33d-4cfe-9f0e-3f13f718dfb9)

**Comment by pafuhana1213** [comment]
https://github.com/pafuhana1213/KawaiiPhysics/commit/0142b3fd79db63d3b1ed83875fe0d389c91f273b
