### ISSUE TITLE
[BUG] CalcBoneLength(ModifyBones[0], BoneContainer.GetRefPoseCompactArray()); 

### ISSUE THREAD

**Issue by zjw1996** [pafuhana1213/KawaiiPhysics#144]
UE4，The array length obtained by GetRefPoseCompactArray is inconsistent with the refbone length, resulting in an array out-of-bounds crash

**Comment by pafuhana1213** [comment]
Hi @zjw1996,Sorry for my late reply.

Unfortunately Kawaii no longer supports UE4, if you are experiencing issues with UE5.2 or later please let me know and I'll be happy to help.
