### ISSUE TITLE
StructUtils is deprecated in UE5.5 

### ISSUE THREAD

**Issue by lordrex34** [pafuhana1213/KawaiiPhysics#148]
StructUtils is deprecated in UE5.5 and project doesn't compile.

Now StructUtils is part of the Engine as I perceived.

UE5.5 compatibility:
https://gist.github.com/lordrex34/d1dee4069390c1423b461ff09d2b65fe

**Comment by pafuhana1213** [comment]
Hi guys!
Sorry for my late support... I've released UE5.5 support now!
please check it! thanks!
https://github.com/pafuhana1213/KawaiiPhysics/discussions/150
