### ISSUE TITLE
Module type of KawaiiPhysicsEd causes standalone development build to fail

### ISSUE THREAD

**Issue by DennyLindberg** [pafuhana1213/KawaiiPhysics#15]
If the game is run in standalone (development build) the KawaiiPhysicsEd module will be missing and the animation blueprint will break. (log will complain about the missing module) We found the issue to be related to the module type being set to **EditorNoCommandlet**. The plugin is still working in PIE and release builds however.

`{
   "Name": "KawaiiPhysicsEd",
   "Type": "EditorNoCommandlet",
   "LoadingPhase": "PreDefault"
}`

We fixed this in our project by setting the module type to **DeveloperTool**. Now it works in all builds.

`{
   "Name": "KawaiiPhysicsEd",
   "Type": "DeveloperTool",
   "LoadingPhase": "PreDefault"
}`

We believe this is related to standalone development builds needing access to animgraphnodes for debugging.

**Comment by polymationgames-ta** [comment]
情報ありがとうございます。
私のプロジェクトもこの対処で、問題を
解決出来ました。

![20200216](https://user-images.githubusercontent.com/51405097/74592886-0aba6f80-5069-11ea-92f9-303caa1e2b92.jpg)

**Comment by pafuhana1213** [comment]
Hi DennyLindberg, polymationgames-ta

Thank you for your report! The following commit may fix this issue.
不具合報告ありがとうございます！以下のコミットで修正しました！
https://github.com/pafuhana1213/KawaiiPhysics/commit/8b9a17384b4ab003a360e278fae9cc1a7a5451e6
