### ISSUE TITLE
UE4 4.25パケット化したエラーを実行し,解答に感謝する

### ISSUE THREAD

**Issue by jhddhr1990** [pafuhana1213/KawaiiPhysics#23]
![捕获](https://user-images.githubusercontent.com/58381755/89734169-0eb1d200-da8d-11ea-81a1-2b911db32c59.JPG)

**Comment by pafuhana1213** [comment]
Hi jhddhr1990 ,

Would you please give me how to reproduce it?
Thanks

**Comment by pafuhana1213** [comment]
https://github.com/pafuhana1213/KawaiiPhysics/issues/1 と重複するので一旦クローズ
