### ISSUE TITLE
4.25から4.26へのアプデについて

### ISSUE THREAD

**Issue by ayayan** [pafuhana1213/KawaiiPhysics#31]
はじめまして！
素敵なプラグインをありがとうございます！
愛用させていただいています！

KawaiiPhysicsを導入している4.25のプロジェクトを4.26にバージョンアップしようとした際に、

"The following modules are missing or built with a different engine version:
KawaiiPhysics
KawaiiPhysicsEd
Would you like to rebuild them now?"

と表示され、"はい"を選択しましたところ、

"〇〇〇〇 could not be compiled. Try rebuilding from source manually."

と表示され、起動できませんでした…。

この問題がKawaiiPhysicsの問題なのか、わかりませんでしたので、
この結果になった流れをお伝えさせていただきます。

最初に4.26にバージョンアップさせた際、上記のエラーが出て、
このときは、KawaiiPhysicsのバージョンが1.6.0のままでしたので、
KawaiiPhysics 1.7.0 のzipを解凍し、中身のpluginフォルダにあるKawaiiPhysicsフォルダを
作業プロジェクトのpluginフォルダにあるバージョン1.6.0のKawaiiPhysicsフォルダに上書きしました。

そして、作業プロジェクトを複製して、作業プロジェクト内の"プロジェクト名.uproject"を右クリックし、
"switch unreal engine version"を選び、4.26を選択し起動させてみたところ、
同じエラーが出て、起動ができませんでした…。

お忙しいところ恐縮ですが、
よろしくお願いします。。

**Comment by pafuhana1213** [comment]
ダイアログメッセージにある通り、プラグインがビルドされた際のエンジンバージョンと異なるバージョンのエンジンで使用する場合は自前でビルドする必要があります。そのため、VisualStudioなどのビルド環境がない場合はプラグインを使用することができません。
https://unrealengine.hatenablog.com/entry/2015/05/20/220000　（今だとVS2017以降になります）

もしビルド環境が構築出来ない場合は、先程UE4.26版のパッケージをアップしたのでこちらをご利用ください。
https://github.com/pafuhana1213/KawaiiPhysics/releases/tag/20201202-v1.7.0

**Comment by ayayan** [comment]
対応ありがとうございました！！

ビルド環境はあるのになぜかプラグインが一緒にアプデしてくれなかったので、

ハテナだったのですが、さきほど原因がやっとみつかりました！！

なので、もしものために情報を共有させてください。

作業プロジェクトを起動するときにはVisual Studio 2019を認識してたのですけど、起動後になぜか認識しなくなってる現象がありました。。笑

エンジン改造等をしてませんでしたので、
エンジン側ではなく、Visual Studio 2019側が変なのかなと、

Visual Studio 2019を1度全部アンインストールし、パソコン再起動後に再インストールしましたところ、

正常にプラグイン入りでも4.25から4.26にアプデ出来ました！

今日は、Twitterの方でお騒がせしてしまい申し訳ありませんでした。

ですが、真摯な対応をしてくだり、ありがとうございます！

これからもKawaiiPhysicsを応援しています！
素敵なプラグインありがとうございます！


2020年12月5日(土) 17:25 pafuhana1213 <notifications@github.com>:
