### ISSUE TITLE
Scarlet Nexus is also using this plugin

### ISSUE THREAD

**Issue by BelovedTomboyishGirl** [pafuhana1213/KawaiiPhysics#35]
You can update this:
https://github.com/pafuhana1213/KawaiiPhysics/wiki/%E6%8E%A1%E7%94%A8%E5%AE%9F%E7%B8%BE-Adoption

On there Unreal Project file there is this line:
`		{
			"Name": "KawaiiPhysics",
			"Enabled": true
		},
`

Have a nice day o/

**Comment by pafuhana1213** [comment]
Thanks!
