### ISSUE TITLE
KawaiiPhysicsプラグインrebuildについて

### ISSUE THREAD

**Issue by TypezeroKenyu-shitsu** [pafuhana1213/KawaiiPhysics#36]
はじめまして須田と申します。
UE4.26.2では問題なくビルドして使えています。
UE4.26.2 for Aximmetryと言うAximmetry版Unreal Editorがあり
こちらでビルトすると下記のようなエラーが出てしまいビルト出来ません。

"KawaiiPhysicsSample could not be compiled. Try rebuilding from source manually."

ログファイルを見てみると
Running C:/Program Files/Aximmetry DE/UnrealEngine/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Win64 -Project="C:/Users/user/Desktop/test/KawaiiPhysics-master/KawaiiPhysicsSample.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
ERROR: Unable to find target of type 'Editor' for project 'C:\Users\user\Desktop\test\KawaiiPhysics-master\KawaiiPhysicsSample.uproject'
と言うエラーが出ているのですが自力で解決できず質問いたしました。

Aximmetry版のUnrealと言うことで少し特殊な件ではありますが
何か心当たりがあればアドバイスなど頂けると助かります。。。

**Comment by pafuhana1213** [comment]
こちら遅くなって申し訳ありません。
Aximmetry版は触ったことがないのですが、その問題の場合はC++プロジェクトにしていただいてVisualStudioからプラグインをビルドしていただけると解決するはずです。

それでもまだ解決しない場合はより詳細な情報を添えてReopenしていただけますと幸いです。
よろしくお願いいたします。
