### ISSUE TITLE
Package error 4.26

### ISSUE THREAD

**Issue by Rudikus** [pafuhana1213/KawaiiPhysics#37]
Gives out an error when trying to pack a project in engine version 4.26. I put the plugin on a clean project.

**Comment by rafabrum1** [comment]
Same thing happening to me

**Comment by rafabrum1** [comment]
For those who had the same issue, put the plugin on the PROJECT folder, not in the ENGINE folder for 4.26.

**Comment by ycqchang** [comment]
It can be packaged in the PROJECT folder. But when running, it will prompt that the plugin cannot be found, and the error exits 2.6 and 2.7.

**Comment by pafuhana1213** [comment]
Perhaps you need to convert your BP project to a C ++ project.
If the cause is other than that, please reopen with detailed information.
