### ISSUE TITLE
UE5 crash when using Break/Make AnimNode_KawaiiPhysicsSetting

### ISSUE THREAD

**Issue by wdw89** [pafuhana1213/KawaiiPhysics#41]
When Creating node of Break/Make AnimNode_KawaiiPhysicsSetting, UE5 crash

**Comment by pafuhana1213** [comment]
Hi,
I can't repro this issue. Probably, a lot of update of UE5 fix this.

if still repro in your project, please share with me detail infos and how to repro this
thanks
