### ISSUE TITLE
Limits Data Asset not showing for UE5 Projects

### ISSUE THREAD

**Issue by eatmylazer** [pafuhana1213/KawaiiPhysics#42]
Limits Data Asset is not showing any kind of information in any UE5 project. 
You're able to create one. Once it's open though, there is no information showing to add the Capsule/Sphere/Planar limits. 

It looks like it's working properly on UE4 projects though.

![001](https://user-images.githubusercontent.com/41389488/136697539-4472bf87-ace3-4a94-9ec2-1dc18cd371f6.jpg)
![002](https://user-images.githubusercontent.com/41389488/136697541-ecf85635-5602-4698-abde-884298592ba8.jpg)

**Comment by ameaninglessname** [comment]
Could you pull the detail panel from the "Window" drop down in the toolbar?

**Comment by eatmylazer** [comment]
What a rookie mistake I've made here. lol
Thanks @ameaninglessname, everything seems to be working just fine now. I'll close the issue
