### ISSUE TITLE
4.27?

### ISSUE THREAD

**Issue by LastOneOnline** [pafuhana1213/KawaiiPhysics#43]
Hello, I'm having a little trouble upgrading the plugin to version 4.27, would it be possible to update the plugin please?

**Comment by shukenmg** [comment]
What is the issue?
I use this plugin on 4.27 without any problems.

**Comment by LastOneOnline** [comment]
I try to use thé plugin on 4.27 but it’s don t build on visual studio, what
version did you use for it? Cause i try 5 ans 4.26.
In plugin section on sofware unreal engine it just don t show kawaii plugin
and impossible to use bide if i can t select plugin

**Comment by LastOneOnline** [comment]
thank you ! finally i just download again and i dn t know how but its work
lol.
Btw AMAZING plugin i love it so much !! :D
