### ISSUE TITLE
module ‘KawaiiPhysics’ could not be found,Plugin no longer works

### ISSUE THREAD

**Issue by ycqchang** [pafuhana1213/KawaiiPhysics#49]
Plugin ‘KawaiiPhysics’ failed to load because module ‘KawaiiPhysics’ could not be found. Please ensure the plugin is properly installed otherwise consider disabling the plugin for this project.

ue4 2.62  2.7  vs2017

It can be used normally in the editor, but the release package will not be available.

**Comment by pafuhana1213** [comment]
Hi,
Perhaps you need to convert your BP project to a C ++ project.
If the cause is other than that, please reopen with detailed information.

**Comment by ycqchang** [comment]
Thanks for your reply, I will try it and see if it works.

**Comment by ycqchang** [comment]
BP project to a C ++ project.
UATHelper: Packaging (Windows (64-bit)):     [3/5] Module.NativizedAssets.cpp
UATHelper: Packaging (Windows (64-bit)):     D:\new game\wdxm\Intermediate\Plugins\NativizedAssets\Windows\Game\Source\NativizedAssets\Public\ppppp_Skeleton_AnimBlueprint__pf1010915279.h(5): fatal error C1083: Unable to open include file: “../Plugins/KawaiiPhysics/Source/KawaiiPhysics/Public/AnimNode_KawaiiPhysics.h”: No such file or directory
UATHelper: Packaging (Windows (64-bit)): Took 74.8811268s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool failed. See log for more details. (C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\d+Epic+Games+UE_4.26\UBT-wdxm-Win64-Development.txt)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED

**Comment by ycqchang** [comment]
project files 
https://drive.google.com/file/d/1IoczQszNPx1rOS4YCyUZEzwRDPv4Vxk4/view?usp=sharing
