### ISSUE TITLE
UE5 official release

### ISSUE THREAD

**Issue by Rwanlink** [pafuhana1213/KawaiiPhysics#50]
Everything was working well with UE5 Preview 1 and Preview 2 but with the official release today, Unreal is not able to open kawaii Physics anymore. Anyone got an idea?

![Screenshot_82](https://user-images.githubusercontent.com/52636530/161826617-bf5b4497-74e6-4276-b5f4-85d498e304fb.png)
![Screenshot_81](https://user-images.githubusercontent.com/52636530/161826618-a38cc085-b107-4335-995f-35d3ce868e4a.png)

**Comment by Rwanlink** [comment]
Thank you so much! It worked!

**Comment by Max-ChenFei** [comment]
Hi Rwanlink, can you share the plugin for UE5?  Thanks a lot.

**Comment by pafuhana1213** [comment]
Hi guys, 
thank you for your help! and sorry for my late reply.

I have updated my plugin to UE5.0 now!
https://github.com/pafuhana1213/KawaiiPhysics/commit/7a33a40e2afd64a4a4f1e7170ed813c4dfe9aaf4
https://github.com/pafuhana1213/KawaiiPhysics/releases/tag/20220411-v1.8.0
