### ISSUE TITLE
Capsule collision is not working properly

### ISSUE THREAD

**Issue by NyakoCombo** [pafuhana1213/KawaiiPhysics#53]
![image](https://user-images.githubusercontent.com/60848100/168011779-4143d2e5-37ce-4866-93bd-b56630949230.png)
![image](https://user-images.githubusercontent.com/60848100/168011803-16834a22-51e4-46b2-b3c1-565498ad2d03.png)
 
 私のスカートの骨格の数と関係がありますか。

**Comment by shukenmg** [comment]
Did you manage to fix it?

**Comment by NyakoCombo** [comment]
> 你修好了吗？ 何とか直りましたか？

No solution.. So combined with a portion of the pre-calculated baking

**Comment by shukenmg** [comment]
Ok, thank you!

**Comment by pafuhana1213** [comment]
Hi guys
I might be able to give you some good advice if you could share the model, but I know it's difficult. Hmm, I think I should provide a better skirt control sample. But I'm not an artist, so I don't have a model for that... I'm in trouble

Thank you
