### ISSUE TITLE
Whether it can support mobile devices (Android/iOS)?

### ISSUE THREAD

**Issue by shlzxjp** [pafuhana1213/KawaiiPhysics#54]

**Comment by shimizu-izumi** [comment]
KawaiiPhysics supports Windows, Android, IOS, Xbox, PlayStation, and probably Nintendo Switch and Linux. for example, the game Scarlet Nexus, which is available for PlayStation 5, PlayStation 4, Xbox One, Xbox Series, and Windows, uses KawaiiPhysics. Another example is Tower of Fantasy which is available for Windows, Android, and IOS and uses KawaiiPhysics.

**Comment by pafuhana1213** [comment]
Hi, he's right. This plugin doesn't use any platform specific features, so it will probably work on all platforms.

Please let me know if there is an environment that does not work.
thanks!
