### ISSUE TITLE
Capsule limit

### ISSUE THREAD

**Issue by pasunna** [pafuhana1213/KawaiiPhysics#55]
The bone still swing pass the limit when character move fast
if there are kinds of fake physic lock like vertical/horizontal x/y/z only
I think it will easier to adjust some move that don't need or out of the plan
thank you

**Comment by pafuhana1213** [comment]
Hi, your ticket is not issue.
let' move to https://github.com/pafuhana1213/KawaiiPhysics/discussions/67 for Discussion.

thanks!
