### ISSUE TITLE
Master Pose Component

### ISSUE THREAD

**Issue by oivio** [pafuhana1213/KawaiiPhysics#58]
I am trying to create modular parts for hair, skirts etc. At this moment all parts sharing same skeleton and also animation blueprints but setting this to "SetMasterComponent" makes kawaii plugin to do not work?

**Comment by DennyLindberg** [comment]
Old issue but at least here is an answer. The master pose method is the cheapest non-merge variant that does not use animation blueprints to be as cheap as possible. If I recall correctly this includes skipping post process animation blueprints. To use KawaiiPhysics you must have an animgraph, which leaves you with the copy pose from mesh method. It is slightly more costly but supports everything you would expect, including full support for copying pose from **any** skeletal mesh as long as there are matching bones. See the modular character docs for more info.

You can simply switch between master pose and copy pose based on if you need an anim instance or not.

https://docs.unrealengine.com/4.27/en-US/AnimatingObjects/SkeletalMeshAnimation/WorkingwithModularCharacters/

**Comment by pafuhana1213** [comment]
Hi guys and thanks [DennyLindberg](https://github.com/DennyLindberg)!

His comment is correct. Additional processing does not work with MasterComponent. When using this plugin, it is recommended to use the Copy ~ node.

Thank you
