### ISSUE TITLE
胶囊碰撞无法正常工作，collision failure. 

### ISSUE THREAD

**Issue by guangliner** [pafuhana1213/KawaiiPhysics#59]
![image](https://user-images.githubusercontent.com/45335688/177003600-bdacc09b-aada-45ba-94c8-5c17b24529f6.png)
The animated blueprint capsule collision is working properly.
![image](https://user-images.githubusercontent.com/45335688/177003745-34933686-c34d-4595-a8b5-ef591d290d14.png)
Enter the scene play, character capsule collision failure. 
I need your help. Thank you.

**Comment by SFBB** [comment]
Have you enabled AngleLimit?

**Comment by guangliner** [comment]
Yes,I have.   I just want to make the effect of the skirt solution, do you have a better way.  Thank you .

**Comment by SFBB** [comment]
Have you tried to disable it? The LimitAngle will pull the bone chain back and cause collisions to push it backward.

**Comment by guangliner** [comment]
I have disabled LimitAngle, no collision effect either,Can't KawaiiPhysics use skirt mesh?

**Comment by pafuhana1213** [comment]
Hmm, it seems difficult to solve without specific information such as settings and assets you are using. First of all, please refer to the skirt setting in the sample

If you share this asset, I might be able to publish a good sample for skirt
Thank you

**Comment by guangliner** [comment]
I have put the example in the email, thank you for taking the time to help me solve the problem.










At 2022-12-03 16:54:03, "pafuhana1213" ***@***.***> wrote:

Hmm, it seems difficult to solve without specific information such as settings and assets you are using. First of all, please refer to the skirt setting in the sample

If you share this asset, I might be able to publish a good sample for skirt
Thank you

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
skirt_Projects.rar (998.62M, 2023年1月27日 18:10 到期)
下载
