### ISSUE TITLE
Crash in void FKawaiiPhysicsEditMode::OnExternalNodePropertyChange (and simple fix)

### ISSUE THREAD

**Issue by sergi-gonzalez** [pafuhana1213/KawaiiPhysics#60]
Hi @pafuhana1213 ,

We are experiencing a crash in the first line of the method FKawaiiPhysicsEditMode::OnExternalNodePropertyChange. 
```
void FKawaiiPhysicsEditMode::OnExternalNodePropertyChange(FPropertyChangedEvent& InPropertyEvent)
{
	USkeletalMeshComponent* SkelComponent = GetAnimPreviewScene().GetPreviewMeshComponent();

	if (!IsValidSelectCollision())
	{
		SelectCollisionIndex = -1;
		SelectCollisionType = ECollisionLimitType::None;
		CurWidgetMode = UE_WIDGET::EWidgetMode::WM_None;
	}
}
```
We have debugged the issue and it happens because the Owner does not contain a valid FAssetEditorModeManager instance.

```
IPersonaPreviewScene& FKawaiiPhysicsEditModeBase::GetAnimPreviewScene() const
{
	return *static_cast<IPersonaPreviewScene*>(static_cast<FAssetEditorModeManager*>(Owner)->GetPreviewScene());
}
```
As the variable SkelComponent is not used in the method (and the calls to to get the variable do not have side effects) we managed to fix the crash simply removing the first line.

You can reproduce the crash doing the following operations in the anim graph view:
- open animation layer asset A
- select a kawaii node N and update any property (make sure that the node is being used to compute the final pose)
- compile asset A
- close asset A
- open asset A again
- select the same kawaii node and update the same property
- compile asset A
- observe the crash

Best regards,

Sergi

**Comment by pafuhana1213** [comment]
Hi! Thank you for your great help!

I remove the line in https://github.com/pafuhana1213/KawaiiPhysics/commit/57b3a15740f3d73b02581b6040a7b9753f13b7d2, so this issue may be fixed.

thanks!
