### ISSUE TITLE
Crashes when updating the constraint limits using characters with multiple LODs

### ISSUE THREAD

**Issue by sergi-gonzalez** [pafuhana1213/KawaiiPhysics#87]
Hi @pafuhana1213,
Your plugin is awesome. Thanks for sharing it.
We are using Kawaii Physics with UE 5.1.
If you character has multiple LODs, the plugin will crash when trying to get CompactPoseIndex in different locations of \KawaiiPhysics\Source\KawaiiPhysics\Private\AnimNode_KawaiiPhysics.cpp 
`const FCompactPoseBoneIndex CompactPoseIndex = Capsule.DrivingBone.GetCompactPoseIndex(BoneContainer);`
when your character is using a LOD different from zero because the DrivingBone indices only work for LOD zero.

We have added the following code to fix the crashes right before calling UpdateSphericalLimits in the method FAnimNode_KawaiiPhysics::EvaluateSkeletalControl_AnyThread.
`
for (auto& Sphere : SphericalLimitsData)
{
	Sphere.DrivingBone.CachedCompactPoseIndex = BoneContainer.MakeCompactPoseIndex(Sphere.DrivingBone.GetMeshPoseIndex(BoneContainer));
}
`
`
for (auto& Capsule : CapsuleLimitsData)
{
	Capsule.DrivingBone.CachedCompactPoseIndex = BoneContainer.MakeCompactPoseIndex(Capsule.DrivingBone.GetMeshPoseIndex(BoneContainer));
}
`
`
for (auto& Planer : PlanarLimitsData)
{
	Planer.DrivingBone.CachedCompactPoseIndex = BoneContainer.MakeCompactPoseIndex(Planer.DrivingBone.GetMeshPoseIndex(BoneContainer));
}
`

Best regards,

s

**Comment by pafuhana1213** [comment]
Hi @sergi-gonzalez ,
Thanks for your report and I committed the following codes to fix this issue.
https://github.com/pafuhana1213/KawaiiPhysics/commit/aff5328299e363d4ae5379c6af0cef16fd104979

Please check it! Thanks!

**Comment by Starlzd** [comment]
> Hi @sergi-gonzalez , Thanks for your report and I committed the following codes to fix this issue. [aff5328](https://github.com/pafuhana1213/KawaiiPhysics/commit/aff5328299e363d4ae5379c6af0cef16fd104979)
> 
> Please check it! Thanks!

Hi, this still has problem. Cause Capsule.DrivingBone.GetCompactPoseIndex(BoneContainer) use CachedCompactPoseIndex, which wll not changes if dynamic lod happpens. Please check it!

**Comment by Starlzd** [comment]
> Hi @sergi-gonzalez , Thanks for your report and I committed the following codes to fix this issue. [aff5328](https://github.com/pafuhana1213/KawaiiPhysics/commit/aff5328299e363d4ae5379c6af0cef16fd104979)
> 
> Please check it! Thanks!

Hi, this still has problem. Cause Capsule.DrivingBone.GetCompactPoseIndex(BoneContainer) use CachedCompactPoseIndex, which wll not changes if dynamic lod happpens. Please check it! @pafuhana1213
