### ISSUE TITLE
SphereLimit、Innerタイプの、コリジョン時のめりこみ解消位置について

### ISSUE THREAD

**Issue by monguri** [pafuhana1213/KawaiiPhysics#9]
SphereLimitに対して、LimitTypeがOuterのときは、コリジョンしたときは
ボーンとSphereLimitの球同士が吸着したような状態まで位置修正していると思います。
一方、LimitTypeがInnerのときは、コリジョンしたときはボーンの位置はSphereLimitの球の表面に位置修正され、ボーンのRadius変数が考慮されません。
Innerと聞いて私がイメージしたのが、ボーンの球がSphereLimitの球の内側に吸着するような位置修正でした。
ただ、これはあくまで個人的な仕様解釈で気になったに過ぎないので、一意見として扱っていただければ幸いです。

**Comment by pafuhana1213** [comment]
ご指摘ありがとうございます！仰る通りかと思いますので対応いたしました！
https://github.com/pafuhana1213/KawaiiPhysics/commit/9329ba47cd6a0ae2017630f5a15f4270d65ff37a

before
![before](https://user-images.githubusercontent.com/8957600/73542540-430e5b00-4478-11ea-9618-661fc603e9dc.png)
after
![after](https://user-images.githubusercontent.com/8957600/73542549-4acdff80-4478-11ea-983e-df8d0a715ddf.png)

**Comment by monguri** [comment]
ありがとうございます！
