### ISSUE TITLE
ue5  crashed when using kawaiiPhysics and ControlRig in levelSsquence

### ISSUE THREAD

**Issue by 15128582506** [pafuhana1213/KawaiiPhysics#94]
SkeletalMesh use kawiiPhysics in Levelsequence. If I add ControlRig(or FKcontrolRig), UE will crash.
I have encountered this issue in both UE5.1 and 5.2.

CrashReporter :
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000000000c0
UnrealEditor_KawaiiPhysics!FAnimNode_KawaiiPhysics::Initialize_AnyThread() 

Is there any way to solve this problem？

**Comment by pafuhana1213** [comment]
Hi @15128582506 , sorry for my late reply!

Would you please share the detail info with me? ( e.g. plugin version, how to repro your issue)
Thanks!

**Comment by 15128582506** [comment]
Hi,@pafuhana1213 

Unreal Engine Version Used：5.21(epic)
kawaii physics Version: 00230523-v1.11.0

You can try this step:
1.create a new project ,add Kawaii Physics to Plugin folder(Reduce interference from others)
2.add Content to the ProJect :Third Person(In order to get a skeletalMesh)
3.create a new Animation Blueprint and  choose SK_Mannequin to bind it
4.add Kawaii physics Node 
5.create a new Level, add a new Level Sequence, add SKM_Manny in Level
6.set SKM_Manny Details : Animation Mode chose Use Animation Blueprint; Anim Class chose NewAnimBlueprint( stpe 3 created)
7.open Level Sequenc(step 5 created),in Sequencer Windows add Track chose SKM_Manny
Then, the Unreal Engine will crash.(add skeletalmesh track will auto add FKcontrolRig track)

The order of steps 6 and 7 can be reversed.

**Comment by pafuhana1213** [comment]
Thanks! I'll try it today.

**Comment by pafuhana1213** [comment]
Sorry for my late replay...
I've committed https://github.com/pafuhana1213/KawaiiPhysics/commit/5a2fd868d9ccbd87b3727614faeb861cd7854d8a to fix your issue 

I'm happy if you try it. Thanks!
