### ISSUE TITLE
アニメーションブループリント作業中にUEがクラッシュします。

### ISSUE THREAD

**Issue by tino1027** [pafuhana1213/KawaiiPhysics#96]
Spherical Limitsでコリジョンをspien_01に追加して、ビューポートで動かそうとするとUEがクラッシュします。
設定が間違っているのか、原因不明です。

**Comment by pafuhana1213** [comment]
@tino1027 
使用しているUEとプラグインのバージョン、そしてクラッシュ時に表示される文字列（コールスタック）をご共有いただけますか？また、関連しそうな情報を可能な限りいただけると問題を特定・解決出来ると思います

よろしくお願いいたします。
